[tool.poetry]
name = "src"
version = "0.2.0"
description = ""
authors = ["Dataroots <info@dataroots.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
Sphinx = "^3.5.4"
flake8 = "^3.9.1"
pytest = "^6.2.3"
pyspark = "^3.1.1"
coverage = "^5.5"
black = "^20.8b1"
bandit = "^1.7.0"
flake8-annotations = "^2.6.2"
flake8-docstrings = "^1.6.0"
mypy = "^0.812"
pytest-mock = "^3.6.0"
    
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
